libgdx/gdx-pay

- gdx-pay-android-openiab/src/com/badlogic/gdx/pay/android/openiab/PurchaseManagerAndroidOpenIAB.java
- gdx-pay-android-ouya/src/com/badlogic/gdx/pay/android/ouya/PurchaseManagerAndroidOUYA.java
Hi, 
i have some issues with crashes, so this is kind of a "hotfix" as long as i couldnt fix the real problem.
i added if (helper != null) { ..... } to avoid crashes in cases where there is no helper object or the wrong purchasemanager has been bound.
this shouldnt be a bad addition
bye
phil
> added if (helper != null) { ..... } to avoid crashes

- gdx-pay/src/com/badlogic/gdx/pay/PurchaseSystem.java
this one adds support for example for com.badlogic.gdx.backends.android.AndroidFragmentApplication
> Support Android Fragment as a super class for gdx.AndroidApplication

- gdx-pay-android-amazon/src/com/badlogic/gdx/pay/android/amazon/PurchaseManagerAndroidAmazon.java
- gdx-pay-android-ouya/src/com/badlogic/gdx/pay/android/ouya/PurchaseManagerAndroidOUYA.java
- gdx-pay-iosrobovm-apple/src/com/badlogic/gdx/pay/ios/apple/PurchaseManageriOSApple.java
> minor changes to amazon and ouya backend...for unique purchase ID and purchase Date

- gdx-pay-android-openiab/src/com/badlogic/gdx/pay/android/openiab/PurchaseManagerAndroidOpenIAB.java
this one fixes:
- several NPEs in OpenIAB integeration (#32, #45)
- fetch of inventory to have all prices for getInformation (#36)
> OpenIAB Inventory and npe fixes

- gdx-pay-android-openiab/src/com/badlogic/gdx/pay/android/openiab/PurchaseManagerAndroidOpenIAB.java
Minor change (better view with [?w=1](https://github.com/libgdx/gdx-pay/pull/48/files?w=1)). Fixes #46.
> Call launchSubscriptionPurchaseFlow when purchasing a subscription

- gdx-pay-android-amazon/src/com/badlogic/gdx/pay/android/amazon/PurchaseManagerAndroidAmazon.java
- gdx-pay-android-openiab/src/com/badlogic/gdx/pay/android/openiab/PurchaseManagerAndroidOpenIAB.java
- gdx-pay-android-ouya/src/com/badlogic/gdx/pay/android/ouya/PurchaseManagerAndroidOUYA.java
- gdx-pay-desktop-apple/src/com/badlogic/gdx/pay/desktop/apple/PurchaseManagerDesktopApple.java
- gdx-pay-gwt-googlewallet/src/com/badlogic/gdx/pay/gwt/googlewallet/PurchaseManagerGwtGoogleWallet.java
- gdx-pay-iosrobovm-apple/src/com/badlogic/gdx/pay/ios/apple/PurchaseManageriOSApple.java
- gdx-pay/src/com/badlogic/gdx/pay/PurchaseManager.java
- gdx-pay/src/com/badlogic/gdx/pay/PurchaseSystem.java
> autoFetchInformation (fix #49)

- gdx-pay-iosrobovm-apple/src/com/badlogic/gdx/pay/ios/apple/PurchaseManageriOSApple.java
On iOS the `getProductByStoreIdentifier` can return null in case the product is not found. The rest of the code assumes it is not null though, which can result in an NPE. This PR fixes this by simply ignoring the transaction when the product is not known.
A simple way to reproduce it would be:
- Create a new product (in itunesconnect and your config)
- Buy the product on your apple device
- Remove the product (in itunesconnect and your config)
- Run the app again and see that it crashes because it cant find the product anymore
This is not a very likely real world production use-case, but a very common use-case when developing/testing. Therefor I think that simply ignoring the transaction (while logging a message) should be enough.
> iOS: don't throw NPE when product is not found

- gdx-pay-iosrobovm-apple/src/com/badlogic/gdx/pay/ios/apple/PurchaseManageriOSApple.java
- fix #62 Unfinished transactions are not restored on iOS
- change docs for PurchaseManageriOSApple
> More ios fixes

- build.gradle
- gdx-pay-android-googleplay/build.gradle
- gdx-pay-tests-android/build.gradle
All versions (dependencies, Android build tools, Android SDK) have been centralized in the root `build.gradle`.
> Centralized versions in root "build.gradle".

- README.md
Warned user not to use gdx-pay-android-openiab.jar AND gdx-pay-android-googleplay.jar
> Warned user not to use openiab.jar AND googleplay.jar

- gdx-pay-iosmoe-apple/src/main/java/com/badlogic/gdx/pay/ios/apple/PurchaseManageriOSApple.java
Fixed some issues with the current port
> Updated iOS Multi-OS Engine support

- gdx-pay-android-googleplay/src/main/java/com/badlogic/gdx/pay/android/googleplay/AndroidGooglePlayPurchaseManager.java
- gdx-pay-android-googleplay/src/main/java/com/badlogic/gdx/pay/android/googleplay/billing/GoogleInAppBillingService.java
- gdx-pay-android-googleplay/src/main/java/com/badlogic/gdx/pay/android/googleplay/billing/V3GoogleInAppBillingService.java
- gdx-pay-android-googleplay/src/main/java/com/badlogic/gdx/pay/android/googleplay/billing/converter/OfferToInAppPurchaseConverter.java
- gdx-pay-android-googleplay/src/test/java/com/badlogic/gdx/pay/android/googleplay/AndroidGooglePlayPurchaseManagerTest.java
- gdx-pay-android-googleplay/src/test/java/com/badlogic/gdx/pay/android/googleplay/billing/V3GoogleInAppBillingServiceTest.java
- gdx-pay-android-googleplay/src/test/java/com/badlogic/gdx/pay/android/googleplay/testdata/GetPurchasesResponseObjectMother.java
This pull request add subscription support to gdx-pay-android-googleplay module. 
This modifications do not support subscription upgrade/downgrade, other features should work.
> Subscription support to gdx-pay-android-googleplay

- gdx-pay-android-googleplay/src/main/java/com/badlogic/gdx/pay/android/googleplay/billing/V3GoogleInAppBillingService.java
> Allow more then 20 SKUs

- gdx-pay-android-amazon/README.md
- gdx-pay-android-amazon/src/com/badlogic/gdx/pay/android/amazon/PurchaseManagerAndroidAmazon.java
As discussed, here is a cleanup for Amazon implementation:
* template JavaDocs deleted
* own logging implementation replaced by calls to Gdx log methods
* IDE warnings improved
> Amazon IAP: Code Cleanup

- gdx-pay-android-googlebilling/src/com/badlogic/gdx/pay/android/googlebilling/PurchaseManagerGoogleBilling.java
> Issue #180 call to endConnection to avoid multiple callbacks and memory leaks

- .travis.yml
- build.gradle
- gdx-pay-tests-android/build.gradle
- gradle/wrapper/gradle-wrapper.properties
These are the changes needed to make the project build successfully.
> #182 Upgrade to Gradle 4.6 / Build Tools 28

- README.md
> typo in dispose() Method

- gdx-pay-server/src/com/badlogic/gdx/pay/server/impl/PurchaseVerifierAndroidAmazon.java
- gdx-pay-server/src/com/badlogic/gdx/pay/server/impl/PurchaseVerifierBase.java
- gdx-pay-server/src/com/badlogic/gdx/pay/server/impl/PurchaseVerifieriOSApple.java
- gdx-pay-server/src/com/badlogic/gdx/pay/server/impl/Security.java
> allow to customise purchase verifiers log output

- README.md
- build.gradle
- gdx-pay-android-googlebilling/src/com/badlogic/gdx/pay/android/googlebilling/PurchaseManagerGoogleBilling.java
Added basic support for subscriptions.
Validated with our app subscriptions are ok. 
Validated for another app, that in-app purchases are still being restored.
Can you have a look? 
Thanks in advance
> Gdx pay android google billing subscriptions

- gdx-pay-android-huawei/src/main/java/com/badlogic/gdx/pay/android/huawei/HuaweiPurchaseManager.java
There was a problem when consumable products was not consumed when restoring transaction. User was not able to buy consumed products because of "already owned error". There was no way to consume product. Now consumable products are consumed when restoring. The same behaviour is adopted in google billing.
> Added consuming products on restore - Huawei.

- gdx-pay-server/src/com/badlogic/gdx/pay/server/impl/Security.java
- gdx-pay-server/src/com/badlogic/gdx/pay/server/util/Base64Util.java
> fix server base64 validate fail

- gdx-pay-android-googlebilling/src/com/badlogic/gdx/pay/android/googlebilling/PurchaseManagerGoogleBilling.java
Google Play Services is now using different parameters to share free trials.
Added support for the new parameter set, also kept supporting the old one
Can anyone using subscriptions review the change?
> Fix #251 support free trial period with NON_RECURRING cycle

- gdx-pay-android-googlebilling/src/com/badlogic/gdx/pay/android/googlebilling/PurchaseManagerGoogleBilling.java
#265: Added reconnection with billing service if initial connection fails, or the connection is lost later on. The behavior is as follows:
* If multiple attempts are needed to create the initial connection, `handleInstallError(...)` of the observer can be invoked multiple times before other methods are invoked.
* If the connection is lost, the observer is not notified of the connection loss, nor of a re-establishment of the connection. After a successful reconnection, the offer details are not fetched again.
> #265: Added reconnection with billing service
